#pragma once

enum Keys
{
	Key_None,
	Key_Space = ' ',
	Key_A = 'a',
	Key_B = 'b',
	Key_C = 'c',
	Key_D = 'd',
	Key_E = 'e',
	Key_F = 'f',
	Key_G = 'g',
	Key_H = 'h',
	Key_I = 'i',
	Key_J = 'j',
	Key_K = 'k',
	Key_L = 'l',
	Key_M = 'm',
	Key_N = 'n',
	Key_O = 'o',
	Key_P = 'p',
	Key_Q = 'q',
	Key_R = 'r',
	Key_S = 's',
	Key_T = 't',
	Key_U = 'u',
	Key_V = 'v',
	Key_W = 'w',
	Key_X = 'x',
	Key_Y = 'y',
	Key_Z = 'z',
	Key_Comma = ',',
	Key_Period = '.',
	Key_Slash = '/',
    Key_Semicolon = ';',
	Key_Backtick = '`',
	Key_LeftParen = '(',
	Key_RightParen = ')',
	Key_LeftBrace = '{',
	Key_RightBrace = '}',
	Key_LeftBracket = '[',
	Key_RightBracket = ']',
    Key_Quote = '\'',
	Key_Backslash = '\\',
	Key_Minus = '-',
	Key_Plus = '+',
	Key_Underscore = '_',
	Key_Equals = '=',
	Key_Question = '?',
	Key_Tilde = '~',
	Key_Digit0 = '0',
	Key_Digit1 = '1',
	Key_Digit2 = '2',
	Key_Digit3 = '3',
	Key_Digit4 = '4',
	Key_Digit5 = '5',
	Key_Digit6 = '6',
	Key_Digit7 = '7',
	Key_Digit8 = '8',
	Key_Digit9 = '9',
	Key_Left = 0x100,
	Key_Right,
	Key_Up,
	Key_Down,
	Key_Enter,
	Key_Ctrl,
	Key_Shift,
	Key_Alt,
	Key_Command,
	Key_Tab,
	Key_Insert,
	Key_Delete,
	Key_Backspace,
	Key_Home,
	Key_End,
	Key_PageUp,
	Key_PageDown,
	Key_Escape,
	Key_F1,
	Key_F2,
	Key_F3,
	Key_F4,
	Key_F5,
	Key_F6,
	Key_F7,
	Key_F8,
	Key_F9,
	Key_F10,
	Key_F11,
	Key_F12,
	Key_NumPad0,
	Key_NumPad1,
	Key_NumPad2,
	Key_NumPad3,
	Key_NumPad4,
	Key_NumPad5,
	Key_NumPad6,
	Key_NumPad7,
	Key_NumPad8,
	Key_NumPad9,
	Key_NumPadDiv,
	Key_NumPadMul,
	Key_NumPadSub,
	Key_NumPadAdd,
	Key_NumPadEnter,
	Key_NumPadPeriod,
	
	Key_MaxKey
};
